"""Shared Streamlit interface helpers."""

from __future__ import annotations

import copy
from io import BytesIO
import re
from pathlib import Path
from typing import Any, Optional
from zipfile import ZIP_DEFLATED, ZipFile

import pandas as pd
import streamlit as st

from src.board import Board
from src.statistics import OpponentComparator, StatisticsTracker
from src.trainer import Trainer
from ui.session import SessionKey

def inject_styles() -> None:
    """Load the interface CSS from its dedicated asset file."""
    css_path = Path(__file__).parent / "assets" / "styles.css"
    css = css_path.read_text(encoding="utf-8")
    st.markdown(css, unsafe_allow_html=True)


class CommonMixin:
    """Methods shared by multiple interface pages."""

    def _inject_styles(self) -> None:
        """Apply the shared interface CSS theme."""
        inject_styles()

    def _is_simple_mode(self) -> bool:
        """Return the single learner-friendly interface used by the project."""
        return True

    def _square_label(self, index: int) -> str:
        """Map internal board indexes 0-8 to learner-facing labels A-I."""
        Board.validate_move_index(index)
        return self.config.project_config.education.square_label(index)

    def _move_label(self, index: Optional[int]) -> str:
        """Return a safe learner-facing square label."""
        return '?' if index is None else self._square_label(int(index))

    def _letterise_play_text(self, value: Any) -> str:
        """
        Convert Play-page move references from internal indexes 0–8 to A–I.

        The conversion is presentation-only. It handles explicit move/square/index
        phrases and the three move lists generated by MENACE/Board explanations:
        Available moves, Legal original-board moves, and Legal matchbox moves.
        State strings, counts, probabilities, bead values and the internal model
        remain unchanged.
        """
        text = str(value)

        def replace_reference(match: re.Match[str]) -> str:
            prefix = match.group(1)
            index = int(match.group(2))
            return f"{prefix}{self._move_label(index)}"

        text = re.sub(
            r"(?i)\b((?:original |visible |board |canonical |matchbox )?"
            r"(?:square|move|index)(?:\s+|\s*[:=]\s*))([0-8])\b",
            replace_reference,
            text,
        )

        def replace_move_list(match: re.Match[str]) -> str:
            label = match.group(1)
            raw_items = match.group(2)
            indexes = re.findall(r"\b[0-8]\b", raw_items)
            letters = ", ".join(
                self._move_label(int(index)) for index in indexes
            )
            return f"{label}[{letters}]"

        return re.sub(
            r"(?i)\b("
            r"Available moves:\s*|"
            r"Legal original-board moves were:\s*|"
            r"Legal matchbox moves were:\s*"
            r")\[([^\]]*)\]",
            replace_move_list,
            text,
        )

    def _lettered_board_text(self, board: Board) -> str:
        """Return a three-row board using A–I for empty squares."""
        cells = [
            value if value != Board.EMPTY else self._square_label(index)
            for index, value in enumerate(board.cells)
        ]
        return "\n".join(
            " | ".join(cells[start:start + 3])
            for start in range(0, Board.BOARD_SIZE, 3)
        )

    def _letterise_matchbox_figure(self, figure: Any) -> Any:
        """Relabel Play-page chart move axes from 0–8 to A–I."""
        for trace in getattr(figure, "data", []):
            values = getattr(trace, "x", None)
            if values is None:
                continue
            converted = []
            changed = False
            for value in values:
                try:
                    index = int(value)
                except (TypeError, ValueError):
                    converted.append(value)
                    continue
                if 0 <= index < Board.BOARD_SIZE and str(value).strip() == str(index):
                    converted.append(self._move_label(index))
                    changed = True
                else:
                    converted.append(value)
            if changed:
                trace.x = converted
        return figure

    def _notify(self, message: str, icon: str = '💡') -> None:
        """Show a short message when the installed Streamlit version supports toast."""
        toast = getattr(st, 'toast', None)
        if callable(toast):
            toast(message, icon=icon)

    def _render_exportable_figure(
        self,
        figure: Any,
        *,
        name: str,
        chart_key: str,
    ) -> None:
        """Render one Plotly figure with a dedicated export button below it.

        HTML is always written because it preserves the interactive chart.  A
        report-ready PNG is written alongside it when Kaleido is available.
        Both files use the Visualiser's validated ``results/figures`` path.
        """
        # Keep exported figures report-ready (white background), but render a
        # separate copy in Streamlit so the chart follows the active Light/Dark
        # app theme. The trace colours are left untouched.
        display_figure = copy.deepcopy(figure)
        if hasattr(display_figure, "update_layout"):
            display_figure.update_layout(
                template=None,
                paper_bgcolor="rgba(0,0,0,0)",
                plot_bgcolor="rgba(0,0,0,0)",
            )
            layout = getattr(display_figure, "layout", None)
            if layout is not None:
                if getattr(layout, "font", None) is not None:
                    layout.font.color = None
                title = getattr(layout, "title", None)
                if title is not None and getattr(title, "font", None) is not None:
                    title.font.color = None

                # The export theme deliberately fixes light-mode axis colours.
                # Clear only those presentation colours on the display copy so
                # Streamlit can provide suitable values for the active theme.
                layout_keys = list(layout.to_plotly_json().keys())
                for axis_name in layout_keys:
                    if not (axis_name.startswith("xaxis") or axis_name.startswith("yaxis")):
                        continue
                    axis = getattr(layout, axis_name, None)
                    if axis is None:
                        continue
                    axis.gridcolor = None
                    axis.zerolinecolor = None
                    axis.linecolor = None
                    if getattr(axis, "tickfont", None) is not None:
                        axis.tickfont.color = None
                    if getattr(axis, "title", None) is not None and getattr(axis.title, "font", None) is not None:
                        axis.title.font.color = None

        st.plotly_chart(
            display_figure,
            width="stretch",
            key=chart_key,
            theme="streamlit",
        )
        evidence_purpose = {
            "learning_curve": "Evidence of how win, loss and draw rates changed during training.",
            "rolling_learning_curve": "A smoothed view that makes the overall learning trend easier to interpret.",
            "outcome_counts": "The exact final number of wins, losses and draws.",
            "outcome_rates": "The final outcome proportions, useful for a concise results summary.",
            "early_late_comparison": "Direct evidence comparing behaviour near the start and end of training.",
            "matchbox_growth": "Evidence of how MENACE's canonical-state memory expanded during training.",
            "comparison_rates": "A complete win, loss and draw comparison across all opponent types.",
            "comparison_win_rate": "A focused comparison of MENACE's success against each opponent.",
            "comparison_loss_rate": "Evidence identifying the opponents that defeated MENACE most often.",
        }.get(name.removeprefix("results_").removeprefix("comparison_"))
        if evidence_purpose:
            st.caption(f"Report evidence: {evidence_purpose}")
        if not st.button(
            "🖼️ Export this figure",
            key=f"export_figure_{chart_key}",
            help=(
                "Save this graph as PNG and interactive HTML in "
                "results/figures."
            ),
        ):
            return

        safe_name = re.sub(r"[^A-Za-z0-9_.-]+", "_", name).strip("_")
        html_path = self.visualiser.export_figure_html(figure, safe_name)
        try:
            png_path = self.visualiser.export_figure_png(figure, safe_name)
        except Exception as exc:
            st.warning(
                f"Saved the interactive figure to {html_path}. PNG export was "
                f"not available: {exc}"
            )
            return

        st.success(
            "Figure exported successfully:\n\n"
            f"- PNG: `{png_path}`\n"
            f"- HTML: `{html_path}`"
        )

    def _figure_download_zip(
        self,
        figures: dict[str, Any],
        *,
        evidence_name: str,
    ) -> bytes:
        """Return report-ready Plotly HTML and PNG figures in one ZIP file."""
        buffer = BytesIO()
        png_failures: list[str] = []
        with ZipFile(buffer, "w", compression=ZIP_DEFLATED) as archive:
            for name, figure in figures.items():
                safe_name = re.sub(r"[^A-Za-z0-9_.-]+", "_", str(name)).strip("_")
                self.visualiser._apply_academic_theme(figure)
                archive.writestr(
                    f"html/{safe_name}.html",
                    figure.to_html(
                        include_plotlyjs="cdn",
                        full_html=True,
                        config={
                            "displaylogo": False,
                            "responsive": True,
                            "toImageButtonOptions": {"format": "png", "scale": 2},
                        },
                    ),
                )
                try:
                    archive.writestr(
                        f"png/{safe_name}.png",
                        figure.to_image(format="png", scale=2),
                    )
                except Exception:
                    png_failures.append(safe_name)

            note = [
                f"MENACE {evidence_name} figure bundle",
                "",
                "The html folder contains interactive graphs.",
                "The png folder contains report-ready images.",
            ]
            if png_failures:
                note.extend(
                    [
                        "",
                        "PNG creation was unavailable for: " + ", ".join(png_failures),
                        "The HTML versions are still included and can export PNG from their camera button.",
                    ]
                )
            archive.writestr("README.txt", "\n".join(note) + "\n")
        return buffer.getvalue()

    def _render_welcome_guide(self) -> None:
        """Show short instructions and an optional visual demonstration."""
        self._render_watch_demo()
        if st.session_state.get(SessionKey.SHOW_DEMO, False):
            return
        if not st.session_state.get(SessionKey.SHOW_WELCOME, True):
            return

        with st.container(border=True):
            if self._is_simple_mode():
                st.markdown("### 👋 Meet MENACE")
                st.write(
                    "MENACE is a simple example of machine learning. It learns "
                    "from the result of each game rather than being told every "
                    "best move in advance."
                )
                st.info(
                    "**What are the matchboxes and beads?** Each different board "
                    "situation is stored as one matchbox. Inside it, each coloured "
                    "bead points to one legal square. A square with more beads is "
                    "more likely to be selected. After a win, helpful choices gain "
                    "beads; after a loss, an unhelpful choice may lose a bead. This "
                    "reward-and-penalty process is how MENACE gradually changes its "
                    "behaviour."
                )
                st.markdown("#### Start here")
                st.caption(
                    "Follow these four steps. The page explains every MENACE "
                    "choice, so no previous machine-learning knowledge is needed."
                )
                st.markdown(
                    """
                    <div class='learning-strip'>
                      <div class='learning-step'><span class='step-badge'>1</span><b>Play X</b><br><small>Choose an empty lettered square A–I.</small></div>
                      <div class='learning-step'><span class='step-badge'>2</span><b>Open the matchbox</b><br><small>MENACE finds the box for the current board and draws a bead.</small></div>
                      <div class='learning-step'><span class='step-badge'>3</span><b>See the choice</b><br><small>The bead points to the square MENACE plays, and the reason is shown.</small></div>
                      <div class='learning-step'><span class='step-badge'>4</span><b>See the reward</b><br><small>At the end, the selected beads are rewarded or reduced.</small></div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )
                demo_col, play_col = st.columns(2)
                if demo_col.button("▶ Watch a short visual demo", width="stretch", type="primary"):
                    st.session_state[SessionKey.SHOW_DEMO] = True
                    st.session_state[SessionKey.DEMO_STEP] = 0
                    st.rerun()
                if play_col.button("Start playing", width="stretch", type="primary"):
                    st.session_state[SessionKey.SHOW_WELCOME] = False
                    st.rerun()
            else:
                st.markdown(f"### 👋 {self.config.welcome_title}")
                st.write(self.config.welcome_text)
                st.info(
                    "The detailed view shows internal board indexes, canonical states, "
                    "symmetry mappings and exact probabilities."
                )
                walkthrough_col, close_col = st.columns(2)
                if walkthrough_col.button(
                    "▶ Start detailed walkthrough",
                    key="start_technical_walkthrough",
                    width="stretch",
                    type="primary",
                ):
                    st.session_state[SessionKey.TECH_SHOW_DEMO] = True
                    st.session_state[SessionKey.TECH_DEMO_STEP] = 0
                    st.session_state[SessionKey.SHOW_WELCOME] = False
                    st.rerun()
                if close_col.button(
                    "Close guide",
                    key="close_welcome",
                    width="stretch",
                ):
                    st.session_state[SessionKey.SHOW_WELCOME] = False
                    st.rerun()

    def _normalise_history(self, history: pd.DataFrame) -> pd.DataFrame:
        """Return a copy of a training history with expected columns normalised."""
        df = history.copy()
        if 'opponent_wins' not in df.columns and 'random_wins' in df.columns:
            df['opponent_wins'] = df['random_wins']
        if 'random_wins' not in df.columns and 'opponent_wins' in df.columns:
            df['random_wins'] = df['opponent_wins']
        return df

    def _show_exported_paths(self, exported: dict[str, Path]) -> None:
        """Show exported evidence paths as a readable table."""
        if not exported:
            return
        st.dataframe(pd.DataFrame([{'figure': name, 'path': str(path)} for name, path in exported.items()]), width="stretch")

    def _latest_symmetry_mapping_record(self) -> Optional[dict[str, Any]]:
        """Return the latest stored MENACE symmetry-mapping record, if present."""
        mappings = st.session_state.get(SessionKey.SYMMETRY_MAPPINGS, [])
        if not mappings:
            return None
        return mappings[-1]

    @staticmethod
    def _explain_board_state_from_string(state: str) -> str:
        """Return Board.explain_state() for a stored compact board state."""
        return Board.from_string(state).explain_state()


    @staticmethod
    def _friendly_join(items: list[str]) -> str:
        """Join short learner-facing labels using natural English."""
        cleaned = [str(item).strip() for item in items if str(item).strip()]
        if not cleaned:
            return ""
        if len(cleaned) == 1:
            return cleaned[0]
        if len(cleaned) == 2:
            return f"{cleaned[0]} and {cleaned[1]}"
        return ", ".join(cleaned[:-1]) + f", and {cleaned[-1]}"

    def _simple_result_update_sentence(self) -> str:
        """Return one short sentence linking the final result to bead changes."""
        result = st.session_state.get(SessionKey.LAST_GAME_RESULT)
        rows = st.session_state.get(SessionKey.LAST_BEAD_CHANGES, [])
        labels = [
            self._move_label(int(row["original_move"]))
            for row in rows
            if row.get("original_move") is not None
        ]
        square_text = self._friendly_join(labels)
        if not result:
            return ""
        if result == "win":
            return (
                f"Because MENACE won, it increased the beads for squares {square_text}."
                if square_text else
                "Because MENACE won, it increased the beads for its helpful moves."
            )
        if result == "loss":
            return (
                f"Because MENACE lost, it reduced the beads for squares {square_text}."
                if square_text else
                "Because MENACE lost, it may lose a bead for some moves."
            )
        return (
            f"Because the game was a draw, it made smaller bead changes for squares {square_text}."
            if square_text else
            "Because the game was a draw, the bead changes were smaller."
        )

    def _refresh_decision_records_after_learning(self) -> None:
        """Synchronise stored move snapshots with current post-learning bead counts."""
        menace = st.session_state[SessionKey.MENACE]
        refreshed: list[dict[str, Any]] = []
        for original_record in st.session_state.get(SessionKey.SYMMETRY_MAPPINGS, []):
            record = dict(original_record)
            state = record.get("matchbox_state")
            box = menace.matchboxes.get(str(state)) if state is not None else None
            rows = [dict(row) for row in record.get("probability_rows", [])]
            if box is not None and rows:
                probabilities = box.probabilities()
                for row in rows:
                    move = int(row["matchbox_move"])
                    if move in box.beads:
                        row["beads"] = int(box.beads[move])
                        row["probability"] = float(probabilities.get(move, 0.0))
                record["probability_rows"] = rows
            refreshed.append(record)
        st.session_state[SessionKey.SYMMETRY_MAPPINGS] = refreshed

    @staticmethod
    def _hardest_opponent_types(grouped: pd.DataFrame) -> list[str]:
        """Return every opponent tied for the lowest MENACE win rate."""
        if grouped.empty:
            return []
        minimum = float(grouped["win_rate"].min())
        return [
            str(value)
            for value in grouped.loc[
                grouped["win_rate"].sub(minimum).abs() < 1e-12,
                "opponent_type",
            ].tolist()
        ]

    def _render_simple_evidence_panel(self, page: str) -> None:
        """
        Show learner-friendly evidence for the current page.

        The panel uses the current session data and keeps detailed tables and
        research terminology inside a collapsed optional section.
        """
        titles = {
            "play": "Evidence from this game",
            "training": "Evidence from this practice run",
            "comparison": "Evidence from the opponent challenge",
            "results": "Graphs from the latest practice run",
            "learning": "Evidence inside MENACE's memory",
        }
        title = titles.get(page, "See the evidence")

        with st.expander(f"📊 {title}", expanded=False):
            st.caption(
                "This optional section presents the same underlying evidence with clear "
                "labels. Teachers, parents, and curious learners can open it "
                "without changing MENACE."
            )

            if page == "play":
                board = st.session_state[SessionKey.BOARD]
                cells = [
                    value if value != Board.EMPTY else self._square_label(index)
                    for index, value in enumerate(board.cells)
                ]
                st.markdown("**Current board evidence**")
                st.dataframe(
                    pd.DataFrame(
                        [cells[0:3], cells[3:6], cells[6:9]],
                        columns=["Left", "Middle", "Right"],
                        index=["Top", "Centre", "Bottom"],
                    ),
                    width="stretch",
                )

                latest = self._latest_symmetry_mapping_record()
                if latest is not None:
                    rows = latest.get("probability_rows", [])
                    if rows:
                        evidence = pd.DataFrame(rows)
                        rename = {
                            "original_board_square": "Square",
                            "beads": "Beads",
                            "probability": "Chance",
                            "selected": "Chosen",
                        }
                        keep = [column for column in rename if column in evidence.columns]
                        evidence = evidence[keep].rename(columns=rename)
                        if "Square" in evidence.columns:
                            evidence["Square"] = evidence["Square"].map(
                                lambda value: self._square_label(int(value))
                            )
                        if "Chance" in evidence.columns:
                            evidence["Chance"] = evidence["Chance"].map(
                                lambda value: f"{float(value):.1%}"
                            )
                        st.markdown("**Latest MENACE choice evidence**")
                        st.dataframe(evidence, width="stretch", hide_index=True)
                else:
                    st.info(
                        "Play until MENACE moves to create choice evidence."
                    )
                return

            if page in {"training", "results"}:
                history = self._normalise_history(
                    st.session_state.get(SessionKey.HISTORY, pd.DataFrame())
                )
                if history.empty:
                    st.info(
                        "Give MENACE some practice first. The learning graphs will "
                        "appear here afterwards."
                    )
                    return

                tracker = StatisticsTracker(history)
                summary = tracker.summary()
                latest = history.iloc[-1]
                cols = st.columns(4)
                cols[0].metric("Games", f"{int(latest['game']):,}")
                cols[1].metric("MENACE wins", f"{int(latest['menace_wins']):,}")
                cols[2].metric("Draws", f"{int(latest['draws']):,}")
                cols[3].metric("Win rate", f"{float(summary.win_rate):.1%}")

                figures = self.visualiser.training_dashboard_figures(history)
                preferred = [
                    ("learning_curve", "How MENACE's results changed"),
                    ("rolling_learning_curve", "Smoothed practice progress"),
                    ("outcome_rates", "Wins, draws, and opponent wins"),
                ]
                shown = 0
                for key, friendly_title in preferred:
                    figure = figures.get(key)
                    if figure is None:
                        continue
                    st.markdown(f"**{friendly_title}**")
                    self._render_exportable_figure(
                        figure,
                        name=f"{page}_{key}",
                        chart_key=f"simple_evidence_{page}_{key}",
                    )
                    shown += 1
                    if shown >= (2 if page == "results" else 1):
                        break

                st.download_button(
                    "Download the practice evidence (CSV)",
                    data=Trainer.evidence_frame(history).to_csv(index=False),
                    file_name="training_evidence.csv",
                    mime="text/csv",
                    key=f"simple_{page}_training_csv",
                )
                st.download_button(
                    "Download all practice graphs and images (ZIP)",
                    data=self._figure_download_zip(
                        figures,
                        evidence_name="practice",
                    ),
                    file_name="menace_practice_figures.zip",
                    mime="application/zip",
                    key=f"simple_{page}_training_figures_zip",
                    help=(
                        "Downloads interactive HTML graphs and report-ready PNG "
                        "images from the latest practice round."
                    ),
                )
                return

            if page == "comparison":
                results = st.session_state.get(
                    SessionKey.COMPARISON,
                    pd.DataFrame(),
                )
                if results is None or results.empty:
                    st.info(
                        "Run the opponent challenge first. Its evidence will appear "
                        "here afterwards."
                    )
                    return

                comparator = OpponentComparator(results)
                rows = comparator.evaluation_rows()
                if rows.empty:
                    st.info("No completed opponent-test rows were found.")
                    return

                grouped = (
                    rows.groupby("opponent_type", as_index=False)
                    .agg(
                        Games=("games", "sum"),
                        MENACE_Wins=("menace_wins", "sum"),
                        Draws=("draws", "sum"),
                        Opponent_Wins=("opponent_wins", "sum"),
                    )
                )
                grouped["MENACE Win Rate"] = (
                    grouped["MENACE_Wins"] / grouped["Games"]
                ).map(lambda value: f"{float(value):.1%}")
                grouped = grouped.rename(
                    columns={
                        "opponent_type": "Opponent",
                        "MENACE_Wins": "MENACE wins",
                        "Opponent_Wins": "Opponent wins",
                    }
                )
                friendly_opponents = {
                    "Random": "The Guesser (Random)",
                    "Heuristic": "The Rule Follower (Heuristic)",
                    "Minimax": "The Careful Thinker (Minimax)",
                }
                grouped["Opponent"] = grouped["Opponent"].map(
                    lambda value: friendly_opponents.get(str(value), str(value))
                )
                st.dataframe(grouped, width="stretch", hide_index=True)
                st.download_button(
                    "Download the comparison evidence (CSV)",
                    data=Trainer.evidence_frame(results).to_csv(index=False),
                    file_name="comparison_evidence.csv",
                    mime="text/csv",
                    key="simple_comparison_evidence_csv",
                )
                comparison_figures = self.visualiser.comparison_dashboard_figures(
                    results
                )
                st.download_button(
                    "Download all comparison graphs and images (ZIP)",
                    data=self._figure_download_zip(
                        comparison_figures,
                        evidence_name="comparison",
                    ),
                    file_name="menace_comparison_figures.zip",
                    mime="application/zip",
                    key="simple_comparison_figures_zip",
                    help=(
                        "Downloads interactive HTML graphs and report-ready PNG "
                        "images from the opponent challenge."
                    ),
                )
                return

            if page == "learning":
                menace = st.session_state[SessionKey.MENACE]
                matchboxes = len(getattr(menace, "matchboxes", {}))
                total_beads = sum(
                    sum(box.beads.values())
                    for box in getattr(menace, "matchboxes", {}).values()
                )
                cols = st.columns(3)
                cols[0].metric(
                    "Practice games completed",
                    f"{int(getattr(menace, 'games_played', 0)):,}",
                )
                cols[1].metric("Matchboxes", f"{matchboxes:,}")
                cols[2].metric("Beads", f"{total_beads:,}")

                matchbox = self._current_matchbox()
                if matchbox is not None:
                    st.markdown("**Current bead probabilities**")
                    try:
                        self._render_exportable_figure(
                            self.visualiser.matchbox_probabilities(matchbox),
                            name="current_matchbox_probabilities",
                            chart_key="simple_learning_evidence_probability",
                        )
                    except Exception:
                        st.dataframe(
                            pd.DataFrame(
                                [
                                    {
                                        "Square": self._square_label(move),
                                        "Beads": beads,
                                        "Chance": (
                                            f"{matchbox.probabilities().get(move, 0.0):.1%}"
                                        ),
                                    }
                                    for move, beads in sorted(matchbox.beads.items())
                                ]
                            ),
                            width="stretch",
                            hide_index=True,
                        )
                else:
                    st.info(
                        "Play one move first to create a current matchbox example."
                    )
                return

